<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Form submitted.]]>
    </line>
    <line>
      <![CDATA[Result asserted.]]>
    </line>
    <line>
      <![CDATA["I am in test 2.]]>
    </line>
  </reporter-output>
  <suite started-at="2021-10-13T18:19:43 GMT+08:00" name="Default Suite" finished-at="2021-10-13T18:19:56 GMT+08:00" duration-ms="13161">
    <groups>
    </groups>
    <test started-at="2021-10-13T18:19:43 GMT+08:00" name="07-03- GenReport" finished-at="2021-10-13T18:19:56 GMT+08:00" duration-ms="13161">
      <class name="Form">
        <test-method is-config="true" signature="setup()[pri:0, instance:Form@543588e6]" started-at="2021-10-13T18:19:43 GMT+08:00" name="setup" finished-at="2021-10-13T18:19:51 GMT+08:00" duration-ms="8616" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testOne()[pri:0, instance:Form@543588e6]" started-at="2021-10-13T18:19:51 GMT+08:00" name="testOne" finished-at="2021-10-13T18:19:55 GMT+08:00" duration-ms="3574" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Form submitted.]]>
            </line>
            <line>
              <![CDATA[Result asserted.]]>
            </line>
          </reporter-output>
        </test-method> <!-- testOne -->
        <test-method signature="testThree()[pri:0, instance:Form@543588e6]" started-at="2021-10-13T18:19:55 GMT+08:00" name="testThree" finished-at="2021-10-13T18:19:55 GMT+08:00" duration-ms="4" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at Form.testThree(Form.java:68)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testThree -->
        <test-method signature="testTwo()[pri:0, instance:Form@543588e6]" started-at="2021-10-13T18:19:55 GMT+08:00" name="testTwo" finished-at="2021-10-13T18:19:55 GMT+08:00" duration-ms="0" status="PASS">
          <reporter-output>
            <line>
              <![CDATA["I am in test 2.]]>
            </line>
          </reporter-output>
        </test-method> <!-- testTwo -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:Form@543588e6]" started-at="2021-10-13T18:19:55 GMT+08:00" name="teardown" finished-at="2021-10-13T18:19:56 GMT+08:00" duration-ms="862" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- Form -->
    </test> <!-- 07-03- GenReport -->
  </suite> <!-- Default Suite -->
</testng-results>
